// Copyright (c) 2026 H.P. Gansevoort. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

using MatPlotLibNet.Fidelity;
using MatPlotLibNet.Geo;
using MatPlotLibNet.Geo.Projections;
using MatPlotLibNet.Models;
using MatPlotLibNet.Styling;

namespace MatPlotLibNet.Tests.Fidelity.Charts;

/// <summary>v1.7.0 geographic fidelity tests — compared against cartopy reference.
/// Reference fixture generated by tools/mpl_reference/generate.py:
///   pip install cartopy
///   python generate.py --chart geo_robinson
/// Geographic projections inherently vary between implementations
/// (Natural Earth data resolution, projection coefficient precision, antialiasing) —
/// so tolerances are looser than for standard Cartesian charts.
/// </summary>
public class GeoFidelityTests : FidelityTest
{
    [Theory]
    [InlineData("classic")]
    [InlineData("v2")]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 150, Ssim = 0.40, DeltaE = 120)]
    public void Robinson_WorldMap_MatchesCartopy(string themeId)
    {
        var theme = ResolveTheme(themeId);
        if (!FixtureExists(theme, "geo_robinson"))
        {
            Assert.Skip(
                "cartopy reference fixture geo_robinson.png not present in repo — generate via " +
                "'pip install cartopy && python tools/mpl_reference/generate.py --chart geo_robinson --style both' " +
                "to enable this fidelity check (cartopy requires system-level GEOS/PROJ libraries and is " +
                "intentionally excluded from tools/mpl_reference/requirements.txt as a non-hermetic dependency).");
        }

        var proj = GeoProjection.Robinson;
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(theme)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("World Map — Robinson")
                .WithProjection(proj)
                .Ocean(proj, Color.FromHex("#1a3a5c"))
                .Land(proj, Color.FromHex("#2d5a27"))
                .Coastlines(proj, Colors.White, lineWidth: 0.5)
                .Borders(proj, Color.FromHex("#888888"), lineWidth: 0.2))
            .Build();

        AssertFidelity(figure, "geo_robinson");
    }
}
