// Copyright (c) 2026 H.P. Gansevoort. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

using MatPlotLibNet.Fidelity;
using MatPlotLibNet.Indicators;
using MatPlotLibNet.Models;
using MatPlotLibNet.Styling;

namespace MatPlotLibNet.Tests.Fidelity.Charts;

/// <summary>
/// Phase 6 — Financial indicator fidelity tests against pandas_ta reference PNGs.
///
/// The OHLC+volume dataset is generated by a closed-form formula that produces
/// byte-identical values in Python and C# (no RNG — Python PCG64 ≠ C# System.Random).
/// Formula: close = 100 + 5·sin(2πi/25) + 3·sin(2πi/7); high/low/open/volume derived.
/// </summary>
public class IndicatorFidelityTests : FidelityTest
{
    private const int N = 60;

    private static (double[] Open, double[] High, double[] Low, double[] Close, double[] Volume) Ohlc(int n = N)
    {
        var open   = new double[n];
        var high   = new double[n];
        var low    = new double[n];
        var close  = new double[n];
        var volume = new double[n];
        for (int i = 0; i < n; i++)
        {
            close[i]  = 100.0 + 5.0 * Math.Sin(2 * Math.PI * i / 25) + 3.0 * Math.Sin(2 * Math.PI * i / 7);
            high[i]   = close[i] + 1.0 + 0.5 * Math.Abs(Math.Sin(i * 0.5));
            low[i]    = close[i] - 1.0 - 0.5 * Math.Abs(Math.Cos(i * 0.5));
            open[i]   = close[i] + 0.3 * Math.Sin(i * 0.7);
            volume[i] = 2500.0 + 1500.0 * Math.Sin(i * 0.3);
        }
        return (open, high, low, close, volume);
    }

    private static double[] BarIndex(int n)
    {
        var x = new double[n];
        for (int i = 0; i < n; i++) x[i] = i;
        return x;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Overlay indicators (price + indicator on same axes)
    // ─────────────────────────────────────────────────────────────────────────

    [Fact]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 60, Ssim = 0.55, DeltaE = 140)]   // 2 thin lines — pure #0000FF AA-diffuses below top-5 pixel threshold
    public void Sma_20_MatchesPandasTa()
    {
        var (_, _, _, close, _) = Ohlc();
        var x = BarIndex(N);
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(Theme.MatplotlibClassic)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("SMA(20) overlay")
                .Plot(x, close, s => s.Label = "close")
                .Sma(20, i => i.Label = "SMA(20)")
                .SetXLabel("bar")
                .SetYLabel("price")
                .WithLegend())
            .Build();
        AssertFidelity(figure, "ind_sma");
    }

    [Fact]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 60, Ssim = 0.55, DeltaE = 140)]   // same as SMA — thin-line AA diffusion
    public void Ema_20_MatchesPandasTa()
    {
        var (_, _, _, close, _) = Ohlc();
        var x = BarIndex(N);
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(Theme.MatplotlibClassic)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("EMA(20) overlay")
                .Plot(x, close, s => s.Label = "close")
                .Ema(20, i => i.Label = "EMA(20)")
                .SetXLabel("bar")
                .SetYLabel("price")
                .WithLegend())
            .Build();
        AssertFidelity(figure, "ind_ema");
    }

    [Fact]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 70, Ssim = 0.50, DeltaE = 55)]
    public void BollingerBands_20_2_MatchesPandasTa()
    {
        var (_, _, _, close, _) = Ohlc();
        var x = BarIndex(N);
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(Theme.MatplotlibClassic)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("Bollinger Bands(20, 2)")
                .Plot(x, close, s => s.Label = "close")
                .BollingerBands(20, 2.0)
                .SetXLabel("bar")
                .SetYLabel("price")
                .WithLegend())
            .Build();
        AssertFidelity(figure, "ind_bbands");
    }

    [Fact]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 70, Ssim = 0.50, DeltaE = 55)]
    public void Vwap_MatchesPandasTa()
    {
        var (_, _, _, close, volume) = Ohlc();
        var x = BarIndex(N);
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(Theme.MatplotlibClassic)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("VWAP")
                .Plot(x, close, s => s.Label = "close")
                .Indicator(new Vwap(close, volume) { Label = "VWAP" })
                .SetXLabel("bar")
                .SetYLabel("price")
                .WithLegend())
            .Build();
        AssertFidelity(figure, "ind_vwap");
    }

    [Fact]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 80, Ssim = 0.50, DeltaE = 140)]   // thin-line AA diffusion
    public void KeltnerChannels_20_MatchesPandasTa()
    {
        var (_, high, low, close, _) = Ohlc();
        var x = BarIndex(N);
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(Theme.MatplotlibClassic)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("Keltner Channels(20, 2)")
                .Plot(x, close, s => s.Label = "close")
                .Indicator(new KeltnerChannels(high, low, close, 20, 2.0))
                .SetXLabel("bar")
                .SetYLabel("price")
                .WithLegend())
            .Build();
        AssertFidelity(figure, "ind_keltner");
    }

    [Fact]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 100, Ssim = 0.45, DeltaE = 80)]   // ichimoku: multi-line + legend + cloud geometry differences
    public void Ichimoku_MatchesPandasTa()
    {
        var (_, high, low, close, _) = Ohlc(n: 80);
        var x = BarIndex(80);
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(Theme.MatplotlibClassic)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("Ichimoku Cloud")
                .Plot(x, close, s => s.Label = "close")
                .Indicator(new Ichimoku(high, low, close))
                .SetXLabel("bar")
                .SetYLabel("price")
                .WithLegend())
            .Build();
        AssertFidelity(figure, "ind_ichimoku");
    }

    [Fact]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 90, Ssim = 0.50, DeltaE = 60)]
    public void ParabolicSar_MatchesPandasTa()
    {
        var (_, high, low, close, _) = Ohlc();
        var x = BarIndex(N);
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(Theme.MatplotlibClassic)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("Parabolic SAR")
                .Plot(x, close, s => s.Label = "close")
                .ParabolicSar(high, low)
                .SetXLabel("bar")
                .SetYLabel("price")
                .WithLegend())
            .Build();
        AssertFidelity(figure, "ind_psar");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Oscillator panels (indicator on its own axes)
    // ─────────────────────────────────────────────────────────────────────────

    [Fact]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 70, Ssim = 0.50, DeltaE = 55)]
    public void Rsi_14_MatchesPandasTa()
    {
        var (_, _, _, close, _) = Ohlc();
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(Theme.MatplotlibClassic)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("RSI(14)")
                .Rsi(close, 14, i => i.Label = "RSI(14)")
                .SetXLabel("bar")
                .SetYLabel("RSI")
                .WithLegend())
            .Build();
        AssertFidelity(figure, "ind_rsi");
    }

    [Fact]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 110, Ssim = 0.45, DeltaE = 140)]   // MACD line/signal/histogram; pure #0000FF AA-diffusion below top-5
    public void Macd_12_26_9_MatchesPandasTa()
    {
        var (_, _, _, close, _) = Ohlc();
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(Theme.MatplotlibClassic)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("MACD(12, 26, 9)")
                .Indicator(new Macd(close, 12, 26, 9))
                .SetXLabel("bar")
                .WithLegend())
            .Build();
        AssertFidelity(figure, "ind_macd");
    }

    [Fact]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 80, Ssim = 0.50, DeltaE = 60)]
    public void Stochastic_14_3_MatchesPandasTa()
    {
        var (_, high, low, close, _) = Ohlc();
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(Theme.MatplotlibClassic)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("Stochastic(14, 3)")
                .Indicator(new Stochastic(high, low, close, 14, 3))
                .SetXLabel("bar")
                .WithLegend())
            .Build();
        AssertFidelity(figure, "ind_stoch");
    }

    [Fact]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 60, Ssim = 0.55, DeltaE = 55)]
    public void Atr_14_MatchesPandasTa()
    {
        var (_, high, low, close, _) = Ohlc();
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(Theme.MatplotlibClassic)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("Average True Range(14)")
                .Indicator(new Atr(high, low, close, 14) { Label = "ATR(14)" })
                .SetXLabel("bar")
                .SetYLabel("ATR")
                .WithLegend())
            .Build();
        AssertFidelity(figure, "ind_atr");
    }

    [Fact]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 80, Ssim = 0.50, DeltaE = 60)]
    public void Adx_14_MatchesPandasTa()
    {
        var (_, high, low, close, _) = Ohlc();
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(Theme.MatplotlibClassic)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("ADX(14)")
                .Indicator(new Adx(high, low, close, 14))
                .SetXLabel("bar")
                .WithLegend())
            .Build();
        AssertFidelity(figure, "ind_adx");
    }

    [Fact]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 70, Ssim = 0.55, DeltaE = 55)]
    public void Cci_20_MatchesPandasTa()
    {
        var (_, high, low, close, _) = Ohlc();
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(Theme.MatplotlibClassic)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("Commodity Channel Index(20)")
                .Cci(high, low, close, 20, i => i.Label = "CCI(20)")
                .SetXLabel("bar")
                .WithLegend())
            .Build();
        AssertFidelity(figure, "ind_cci");
    }

    [Fact]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 70, Ssim = 0.55, DeltaE = 55)]
    public void WilliamsR_14_MatchesPandasTa()
    {
        var (_, high, low, close, _) = Ohlc();
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(Theme.MatplotlibClassic)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("Williams %R(14)")
                .WilliamsR(high, low, close, 14, i => i.Label = "Williams %R(14)")
                .SetXLabel("bar")
                .WithLegend())
            .Build();
        AssertFidelity(figure, "ind_williamsr");
    }

    [Fact]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 60, Ssim = 0.55, DeltaE = 55)]
    public void Obv_MatchesPandasTa()
    {
        var (_, _, _, close, volume) = Ohlc();
        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(Theme.MatplotlibClassic)
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("On-Balance Volume")
                .Obv(close, volume, i => i.Label = "OBV")
                .SetXLabel("bar")
                .SetYLabel("OBV")
                .WithLegend())
            .Build();
        AssertFidelity(figure, "ind_obv");
    }
}
