// Copyright (c) 2026 H.P. Gansevoort. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

using MatPlotLibNet.Fidelity;
using MatPlotLibNet.Models;
using MatPlotLibNet.Styling;

namespace MatPlotLibNet.Tests.Fidelity.Charts;

/// <summary>v1.7.0 axis features (broken-axis, symlog) compared against matplotlib.
/// Reference fixtures generated by tools/mpl_reference/generate.py:
///   python generate.py --chart broken_y symlog
/// </summary>
public class V170AxisFeaturesFidelityTests : FidelityTest
{
    [Theory]
    [InlineData("classic")]
    [InlineData("v2")]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 100, Ssim = 0.50, DeltaE = 80)]
    public void BrokenY_MatchesMatplotlib(string themeId)
    {
        // Data with low values 0..18 and high values 100..118 — break removes 25..85.
        // Matplotlib's recommended pattern uses two stacked subplots with shared X.
        // MatPlotLibNet's WithYBreak should produce visually equivalent output.
        double[] x = Enumerable.Range(0, 20).Select(i => (double)i).ToArray();
        double[] y = x.Select(v => v < 10 ? v * 2 : v * 2 + 80).ToArray();

        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(ResolveTheme(themeId))
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("Broken Y-Axis")
                .Plot(x, y, s => s.Label = "Data")
                .WithYBreak(25, 85)
                .SetXLabel("x")
                .WithLegend(LegendPosition.UpperLeft))
            .Build();

        AssertFidelity(figure, "broken_y");
    }

    [Theory]
    [InlineData("classic")]
    [InlineData("v2")]
    [Trait("Category", "Fidelity")]
    [FidelityTolerance(Rms = 100, Ssim = 0.50, DeltaE = 80)]
    public void Symlog_MatchesMatplotlib(string themeId)
    {
        // Cubic data x ∈ [-50, 50] spanning ±125000, symlog Y with linthresh=100.
        double[] x = Enumerable.Range(-50, 101).Select(i => (double)i).ToArray();
        double[] y = x.Select(v => v * v * v).ToArray();

        var figure = Plt.Create()
            .WithSize(FigWidth, FigHeight)
            .WithTheme(ResolveTheme(themeId))
            .AddSubPlot(1, 1, 1, ax => ax
                .WithTitle("Symlog Y-Axis — x³")
                .Plot(x, y, s => s.Label = "x³")
                .WithSymlogYScale(linthresh: 100)
                .SetXLabel("x")
                .SetYLabel("x³ (symlog, linthresh=100)")
                .WithLegend(LegendPosition.UpperLeft))
            .Build();

        AssertFidelity(figure, "symlog");
    }
}
