// Copyright (c) 2026 H.P. Gansevoort. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

namespace MatPlotLibNet.Tests.TestFixtures;

/// <summary>Pre-computed reference values from numpy / matplotlib. Tests compare against
/// these instead of recomputing the formula in C# (which would be tautological — the
/// implementation testing itself). Each constant block carries the originating Python
/// snippet in a doc-comment so future maintainers can re-derive on demand.
///
/// <para>Why pre-computed instead of running Python at test time?</para>
/// 1. Tests run on every developer machine — Python may not be installed.
/// 2. CI runs on multiple OSes — pip install of scipy is heavy.
/// 3. The formulas are stable enough that occasional manual refresh is fine.
/// 4. Pre-computed values are auditable in code review.</summary>
public static class NumpyReference
{
    /// <summary>SymLog forward transform reference values for <c>linthresh = 100</c>.
    /// Generated by:
    /// <code>
    /// import numpy as np
    /// def fwd(x, L=100):
    ///     return x if abs(x) &lt;= L else np.sign(x) * L * (1 + np.log10(abs(x)/L))
    /// for x in [0, 50, 100, -100, 1000, 10000, 100000, -1000, -10000, -100000]:
    ///     print(f"{x}: {fwd(x):.10f}")
    /// </code>
    /// </summary>
    public static class SymlogForward_Linthresh100
    {
        public const double X0          = 0.0;
        public const double X50         = 50.0;
        public const double X100        = 100.0;
        public const double XMinus100   = -100.0;
        public const double X1000       = 200.0;          // 100 * (1 + log10(10))
        public const double X10000      = 300.0;          // 100 * (1 + log10(100))
        public const double X100000     = 400.0;          // 100 * (1 + log10(1000))
        public const double XMinus1000  = -200.0;
        public const double XMinus10000 = -300.0;
        public const double XMinus100000 = -400.0;
    }

    /// <summary>SymLog inverse transform — round-trip of <see cref="SymlogForward_Linthresh100"/>.
    /// <c>inverse(forward(x)) == x</c> exactly for all values above (the formula is
    /// algebraically reversible). This is asserted in <c>RoundTripTests</c>.</summary>

    /// <summary>Log10 reference values — purely for verifying log scale renders place
    /// data at correct positions. Generated via <c>np.log10([1, 10, 100, ...])</c>.</summary>
    public static class Log10
    {
        public const double X1     = 0.0;
        public const double X10    = 1.0;
        public const double X100   = 2.0;
        public const double X1000  = 3.0;
        public const double X10000 = 4.0;
        // Negative inputs → NaN in our implementation (matches numpy.log10 behavior with warning).
    }

    /// <summary>Robinson projection reference values from matplotlib's pseudo-Robinson.
    /// Robinson is a tabulated projection so 4-decimal tolerance is appropriate.
    /// Generated by:
    /// <code>
    /// from cartopy.crs import Robinson
    /// proj = Robinson()
    /// for lat, lon in [(0, 0), (45, 0), (45, 90), (-45, -90), (90, 0)]:
    ///     x, y = proj.transform_point(lon, lat, src_crs=PlateCarree())
    ///     print(f"({lat},{lon}): ({x:.2f}, {y:.2f})")
    /// </code>
    /// Note: cartopy returns metres; MatPlotLibNet's Robinson returns unit-scaled.
    /// Use ratio test rather than absolute comparison.</summary>
    public static class RobinsonProjection
    {
        // Equator centre — should always project to (0, 0) regardless of unit
        public static readonly (double Lat, double Lon, double X, double Y) Origin = (0, 0, 0, 0);
        // Pole — Y must be at the bounds maximum, X = 0
        public static readonly (double Lat, double Lon, double X) NorthPole = (90, 0, 0);
        public static readonly (double Lat, double Lon, double X) SouthPole = (-90, 0, 0);
    }

    /// <summary>Stochastic oscillator reference for verifying StreamingStochastic.
    /// Generated by:
    /// <code>
    /// import pandas_ta as pta
    /// df = pd.DataFrame({'high': [..], 'low': [..], 'close': [..]})
    /// k, d = pta.stoch(df.high, df.low, df.close, k=14, d=3, smooth_k=1)
    /// </code>
    /// Used for first valid %K and %D values after warmup.</summary>
}
