// Copyright (c) 2026 H.P. Gansevoort. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

using MatPlotLibNet.Styling;
using MatPlotLibNet.Styling.ColorMaps;

namespace MatPlotLibNet.Tests.Styling;

/// <summary>Verifies <see cref="ReversedColorMap"/> and <see cref="ColorMapRegistry"/>.</summary>
public class ColorMapRegistryTests
{
    // --- ReversedColorMap ---

    [Fact]
    public void ReversedColorMap_InvertsValues()
    {
        var inner = ColorMaps.Viridis;
        var reversed = new ReversedColorMap(inner);

        Assert.Equal(inner.GetColor(1.0), reversed.GetColor(0.0));
        Assert.Equal(inner.GetColor(0.0), reversed.GetColor(1.0));
    }

    [Fact]
    public void ReversedColorMap_NameHasSuffix()
    {
        var reversed = new ReversedColorMap(ColorMaps.Viridis);
        Assert.Equal("viridis_r", reversed.Name);
    }

    [Fact]
    public void ReversedColorMap_DoubleReversalRestoresOriginal()
    {
        var original = ColorMaps.Blues;
        var doubleReversed = new ReversedColorMap(new ReversedColorMap(original));

        Assert.Equal(original.GetColor(0.3), doubleReversed.GetColor(0.3));
    }

    // --- ColorMapRegistry ---

    [Fact]
    public void Registry_GetByName_ReturnsViridis()
    {
        var map = ColorMapRegistry.Get("viridis");
        Assert.NotNull(map);
        Assert.Equal("viridis", map!.Name);
    }

    [Fact]
    public void Registry_GetByName_CaseInsensitive()
    {
        var map = ColorMapRegistry.Get("Viridis");
        Assert.NotNull(map);
    }

    [Fact]
    public void Registry_ReversedAutoGenerated()
    {
        var map = ColorMapRegistry.Get("viridis_r");
        Assert.NotNull(map);
        Assert.Equal("viridis_r", map!.Name);
    }

    [Fact]
    public void Registry_AllBuiltInsRegistered()
    {
        var names = new[]
        {
            // Perceptually-uniform
            "viridis", "plasma", "inferno", "magma", "coolwarm", "blues", "reds",
            "turbo", "jet",
            // Sequential
            "cividis", "greens", "oranges", "purples", "greys",
            "ylorbr", "ylorrd", "orrd", "pubu", "ylgn", "bugn",
            "hot", "copper", "bone", "bupu", "gnbu", "purd", "rdpu", "ylgnbu", "pubugn",
            "cubehelix",
            // Diverging
            "rdbu", "rdylgn", "rdylbu", "brbg", "piyg", "spectral",
            "puor", "seismic", "bwr",
            // Cyclic
            "twilight", "twilight_shifted", "hsv",
            // Seaborn perceptually-uniform
            "rocket", "mako", "crest", "flare", "icefire",
            // Qualitative
            "tab10", "tab20", "set1", "set2", "set3", "pastel1",
            "pastel2", "dark2", "accent", "paired",
        };

        foreach (var name in names)
        {
            Assert.NotNull(ColorMapRegistry.Get(name));
            Assert.NotNull(ColorMapRegistry.Get(name + "_r"));
        }
    }

    [Fact]
    public void Registry_TotalMapCount()
    {
        // 57 base maps × 2 (forward + _r reversed) = 114
        // Custom registrations may add more, so assert >= 114
        Assert.True(ColorMapRegistry.Names.Count() >= 114,
            $"Expected at least 114 registered colormaps (57 × 2), got {ColorMapRegistry.Names.Count()}");
    }

    [Fact]
    public void ColorMapsAll_ReturnsAtLeast114Maps()
    {
        Assert.True(ColorMaps.All.Count() >= 114);
    }

    // --- PerceptualColorMaps2 (Seaborn) ---

    [Theory]
    [InlineData("rocket")]
    [InlineData("mako")]
    [InlineData("crest")]
    [InlineData("flare")]
    [InlineData("icefire")]
    public void PerceptualColorMaps2_ResolvesByName(string name)
    {
        var map = ColorMapRegistry.Get(name);
        Assert.NotNull(map);
        Assert.Equal(name, map!.Name);
    }

    [Theory]
    [InlineData("rocket_r")]
    [InlineData("mako_r")]
    [InlineData("crest_r")]
    [InlineData("flare_r")]
    [InlineData("icefire_r")]
    public void PerceptualColorMaps2_ReversedVariantRegistered(string name)
    {
        var map = ColorMapRegistry.Get(name);
        Assert.NotNull(map);
        Assert.Equal(name, map!.Name);
    }

    [Theory]
    [InlineData("rocket")]
    [InlineData("mako")]
    [InlineData("crest")]
    [InlineData("flare")]
    [InlineData("icefire")]
    public void PerceptualColorMaps2_ZeroAndOneReturnDistinctColors(string name)
    {
        var map = ColorMapRegistry.Get(name)!;
        var low  = map.GetColor(0.0);
        var high = map.GetColor(1.0);
        Assert.NotEqual(low, high);
    }

    [Fact]
    public void Registry_CustomRegistration()
    {
        var custom = new ReversedColorMap(ColorMaps.Blues); // just need any IColorMap
        ColorMapRegistry.Register("my_custom", custom);
        Assert.Same(custom, ColorMapRegistry.Get("my_custom"));
    }

    [Fact]
    public void Registry_UnknownReturnsNull()
    {
        Assert.Null(ColorMapRegistry.Get("nonexistent_colormap_xyz"));
    }
}
