// Copyright (c) 2026 H.P. Gansevoort. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

using System.Reflection;
using MatPlotLibNet.Styling;
using MatPlotLibNet.Styling.ColorMaps;

namespace MatPlotLibNet.Tests.Styling;

/// <summary>Verifies <see cref="ReversedColorMap"/> and <see cref="ColorMapRegistry"/>.</summary>
public class ColorMapRegistryTests
{
    // --- ReversedColorMap ---

    [Fact]
    public void ReversedColorMap_InvertsValues()
    {
        var inner = ColorMaps.Viridis;
        var reversed = new ReversedColorMap(inner);

        Assert.Equal(inner.GetColor(1.0), reversed.GetColor(0.0));
        Assert.Equal(inner.GetColor(0.0), reversed.GetColor(1.0));
    }

    [Fact]
    public void ReversedColorMap_NameHasSuffix()
    {
        var reversed = new ReversedColorMap(ColorMaps.Viridis);
        Assert.Equal("viridis_r", reversed.Name);
    }

    [Fact]
    public void ReversedColorMap_DoubleReversalRestoresOriginal()
    {
        var original = ColorMaps.Blues;
        var doubleReversed = new ReversedColorMap(new ReversedColorMap(original));

        Assert.Equal(original.GetColor(0.3), doubleReversed.GetColor(0.3));
    }

    // --- ColorMapRegistry ---

    [Fact]
    public void Registry_GetByName_ReturnsViridis()
    {
        var map = ColorMapRegistry.Get("viridis");
        Assert.NotNull(map);
        Assert.Equal("viridis", map!.Name);
    }

    [Fact]
    public void Registry_GetByName_CaseInsensitive()
    {
        var map = ColorMapRegistry.Get("Viridis");
        Assert.NotNull(map);
    }

    [Fact]
    public void Registry_ReversedAutoGenerated()
    {
        var map = ColorMapRegistry.Get("viridis_r");
        Assert.NotNull(map);
        Assert.Equal("viridis_r", map!.Name);
    }

    /// <summary>Every colormap the library declares, found the way the registry's own constructor finds them:
    /// the static colormap properties of the seven classes that hold them. A hand-kept list of names went stale
    /// the moment a category was added — it was missing thirteen maps and Okabe-Ito when this replaced it.</summary>
    internal static IColorMap[] DeclaredColorMaps() =>
        [.. new[]
            {
                typeof(ColorMaps), typeof(SequentialColorMaps), typeof(DivergingColorMaps), typeof(CyclicColorMaps),
                typeof(AdditionalColorMaps), typeof(PerceptualColorMaps2), typeof(QualitativeColorMaps),
            }
            .SelectMany(type => type.GetProperties(BindingFlags.Public | BindingFlags.Static))
            .Where(property => typeof(IColorMap).IsAssignableFrom(property.PropertyType))
            .Select(property => (IColorMap)property.GetValue(null)!)];

    [Fact]
    public void TheLibraryShips_TheNumberOfColormapsItSaysItDoes()
    {
        // README, the documentation index, the cookbook index, the heatmaps page, the intro article and
        // ARCHITECTURE all print this number, and until this test none of them was held to it: the old check
        // asked for "at least 114" while the registry had grown to 142, so a map could be lost without a word.
        Assert.Equal(74, DeclaredColorMaps().Length);
        Assert.Equal(148, DeclaredColorMaps().Length * 2);
    }

    [Fact]
    public void EveryColormapTheLibraryDeclares_IsRegisteredWithItsReversedTwin()
    {
        var missing = DeclaredColorMaps()
            .SelectMany(map => new[] { map.Name, map.Name + "_r" })
            .Where(name => ColorMapRegistry.Get(name) is null)
            .ToArray();

        Assert.True(missing.Length == 0,
            "These colormaps are declared and cannot be looked up: " + string.Join(", ", missing));
    }

    [Fact]
    public void EveryColormapName_IsItsOwn()
    {
        // Two maps under one name would leave the registry one short of its count with nothing to show for it.
        var duplicates = DeclaredColorMaps()
            .GroupBy(map => map.Name, StringComparer.OrdinalIgnoreCase)
            .Where(group => group.Count() > 1)
            .Select(group => group.Key)
            .ToArray();

        Assert.True(duplicates.Length == 0, "Declared twice: " + string.Join(", ", duplicates));
    }

    [Fact]
    public void TheRegistry_HoldsEveryBuiltInNameAndReadsThemBack()
    {
        var builtIn = DeclaredColorMaps().SelectMany(map => new[] { map.Name, map.Name + "_r" }).ToArray();

        // A custom registration by another test can add to this registry, so the count is a floor of its own
        // built-ins; what is exact is the list above, and that every one of these names reads back.
        Assert.Equal(148, builtIn.Length);
        Assert.All(builtIn, name => Assert.Equal(name, ColorMaps.Get(name)!.Name));

        // ColorMaps.All is the enumeration a caller reaches for to list what is available.
        var all = ColorMaps.All.Select(map => map.Name).ToArray();
        Assert.Empty(builtIn.Except(all, StringComparer.OrdinalIgnoreCase));
    }

    // --- PerceptualColorMaps2 (Seaborn) ---

    [Theory]
    [InlineData("rocket")]
    [InlineData("mako")]
    [InlineData("crest")]
    [InlineData("flare")]
    [InlineData("icefire")]
    public void PerceptualColorMaps2_ResolvesByName(string name)
    {
        var map = ColorMapRegistry.Get(name);
        Assert.NotNull(map);
        Assert.Equal(name, map!.Name);
    }

    [Theory]
    [InlineData("rocket_r")]
    [InlineData("mako_r")]
    [InlineData("crest_r")]
    [InlineData("flare_r")]
    [InlineData("icefire_r")]
    public void PerceptualColorMaps2_ReversedVariantRegistered(string name)
    {
        var map = ColorMapRegistry.Get(name);
        Assert.NotNull(map);
        Assert.Equal(name, map!.Name);
    }

    [Theory]
    [InlineData("rocket")]
    [InlineData("mako")]
    [InlineData("crest")]
    [InlineData("flare")]
    [InlineData("icefire")]
    public void PerceptualColorMaps2_ZeroAndOneReturnDistinctColors(string name)
    {
        var map = ColorMapRegistry.Get(name)!;
        var low  = map.GetColor(0.0);
        var high = map.GetColor(1.0);
        Assert.NotEqual(low, high);
    }

    [Fact]
    public void Registry_CustomRegistration()
    {
        var custom = new ReversedColorMap(ColorMaps.Blues); // just need any IColorMap
        ColorMapRegistry.Register("my_custom", custom);
        Assert.Same(custom, ColorMapRegistry.Get("my_custom"));
    }

    [Fact]
    public void Registry_UnknownReturnsNull()
    {
        Assert.Null(ColorMapRegistry.Get("nonexistent_colormap_xyz"));
    }

    // --- Petroff (accessible sequences for data visualization, arXiv:2107.02270) ---
    //
    // Three sequences of six, eight and ten colours, each designed so that every pair inside it stays
    // distinguishable for the common forms of colour-vision deficiency. matplotlib ships the same three as
    // style sheets; the values here are its own, so a chart drawn either side of the fence looks the same.

    [Theory]
    [InlineData("petroff6", 6)]
    [InlineData("petroff8", 8)]
    [InlineData("petroff10", 10)]
    public void APetroffSequence_IsRegisteredAndHasTheColoursItsNameCounts(string name, int colors)
    {
        var map = ColorMapRegistry.Get(name);

        Assert.NotNull(map);
        Assert.Equal(name, map!.Name);
        Assert.NotNull(ColorMapRegistry.Get(name + "_r"));
        // A listed map returns one of its colours for every position, so walking the range finds each of them.
        var distinct = Enumerable.Range(0, 1001).Select(step => map.GetColor(step / 1000.0)).Distinct().ToArray();
        Assert.Equal(colors, distinct.Length);
    }

    [Fact]
    public void ThePetroffSequences_CarryMatplotlibsOwnValues()
    {
        Assert.Equal("#5790FC", ColorMapRegistry.Get("petroff6")!.GetColor(0).ToHex());
        Assert.Equal("#7A21DD", ColorMapRegistry.Get("petroff6")!.GetColor(1).ToHex());
        Assert.Equal("#1845FB", ColorMapRegistry.Get("petroff8")!.GetColor(0).ToHex());
        Assert.Equal("#656364", ColorMapRegistry.Get("petroff8")!.GetColor(1).ToHex());
        Assert.Equal("#3F90DA", ColorMapRegistry.Get("petroff10")!.GetColor(0).ToHex());
        Assert.Equal("#92DADD", ColorMapRegistry.Get("petroff10")!.GetColor(1).ToHex());
    }
}
