"""Generate the Unicode bidi tables MatPlotLibNet's UAX#9 implementation reads.

Input (checked in under tools/unicode/ucd/, Unicode Character Database):
  DerivedBidiClass.txt  - every code point's Bidi_Class, as ranges, plus @missing defaults
  BidiBrackets.txt      - the paired brackets (Bidi_Paired_Bracket + Bidi_Paired_Bracket_Type)

Output: two C# source files with one sorted, non-overlapping range table each. The C# side does a
binary search over the ranges; the @missing defaults are materialised as ranges too, so the lookup
needs no second table.

Usage: python generate_bidi_tables.py <ucd-dir> <out-dir>
"""
import re
import sys
from pathlib import Path

CLASSES = [
    "L", "R", "AL", "EN", "ES", "ET", "AN", "CS", "NSM", "BN", "B", "S", "WS", "ON",
    "LRE", "LRO", "RLE", "RLO", "PDF", "LRI", "RLI", "FSI", "PDI",
]
LONG_NAMES = {
    "Left_To_Right": "L", "Right_To_Left": "R", "Arabic_Letter": "AL", "European_Number": "EN",
    "European_Separator": "ES", "European_Terminator": "ET", "Arabic_Number": "AN",
    "Common_Separator": "CS", "Nonspacing_Mark": "NSM", "Boundary_Neutral": "BN",
    "Paragraph_Separator": "B", "Segment_Separator": "S", "White_Space": "WS", "Other_Neutral": "ON",
    "Left_To_Right_Embedding": "LRE", "Left_To_Right_Override": "LRO",
    "Right_To_Left_Embedding": "RLE", "Right_To_Left_Override": "RLO", "Pop_Directional_Format": "PDF",
    "Left_To_Right_Isolate": "LRI", "Right_To_Left_Isolate": "RLI", "First_Strong_Isolate": "FSI",
    "Pop_Directional_Isolate": "PDI",
}
MAX_CP = 0x10FFFF


def parse_range(field: str) -> tuple[int, int]:
    field = field.strip()
    if ".." in field:
        a, b = field.split("..")
        return int(a, 16), int(b, 16)
    v = int(field, 16)
    return v, v


def read_bidi_classes(path: Path) -> tuple[str, list[tuple[int, int, str]]]:
    """Returns (ucd version, sorted non-overlapping ranges covering 0..10FFFF)."""
    version = None
    missing: list[tuple[int, int, str]] = []
    explicit: list[tuple[int, int, str]] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        if version is None:
            m = re.match(r"# DerivedBidiClass-(\d+\.\d+\.\d+)\.txt", raw)
            if m:
                version = m.group(1)
        m = re.match(r"# @missing:\s*([0-9A-F.]+)\s*;\s*(\w+)", raw)
        if m:
            lo, hi = parse_range(m.group(1))
            missing.append((lo, hi, LONG_NAMES[m.group(2)]))
            continue
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        rng, cls = [p.strip() for p in line.split(";")[:2]]
        lo, hi = parse_range(rng)
        explicit.append((lo, hi, cls))
    if version is None:
        raise SystemExit("no version header in " + str(path))

    # Paint: later @missing lines override earlier ones (the file lists the broad default first),
    # explicit assignments override every default.
    table = [None] * (MAX_CP + 1)
    for lo, hi, cls in missing:
        for cp in range(lo, hi + 1):
            table[cp] = cls
    for lo, hi, cls in explicit:
        for cp in range(lo, hi + 1):
            table[cp] = cls
    # Compress to ranges.
    ranges: list[tuple[int, int, str]] = []
    start = 0
    for cp in range(1, MAX_CP + 2):
        if cp > MAX_CP or table[cp] != table[start]:
            ranges.append((start, cp - 1, table[start]))
            start = cp
    return version, ranges


def read_brackets(path: Path) -> tuple[str, list[tuple[int, int, str]]]:
    version = None
    pairs: list[tuple[int, int, str]] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        if version is None:
            m = re.match(r"# BidiBrackets-(\d+\.\d+\.\d+)\.txt", raw)
            if m:
                version = m.group(1)
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        cp, pair, kind = [p.strip() for p in line.split(";")]
        pairs.append((int(cp, 16), int(pair, 16), kind))
    if version is None:
        raise SystemExit("no version header in " + str(path))
    pairs.sort()
    return version, pairs


HEADER = """// <auto-generated>
// Generated by tools/unicode/generate_bidi_tables.py from the Unicode Character Database {version}
// ({source}). Do not edit by hand: regenerate, and the drift test in
// Tst/MatPlotLibNet/Rendering/Text/UnicodeTablesTests.cs will tell you if the two disagree.
// Unicode data files are used under the Unicode License v3 (tools/unicode/ucd/LICENSE).
// </auto-generated>
"""


def emit_classes(version: str, ranges: list[tuple[int, int, str]], out: Path) -> None:
    lines = [HEADER.format(version=version, source="DerivedBidiClass.txt")]
    lines.append("namespace MatPlotLibNet.Rendering.Text;\n")
    lines.append("internal static partial class BidiClassTable")
    lines.append("{")
    lines.append(f'    /// <summary>The Unicode Character Database version these ranges were generated from.</summary>')
    lines.append(f'    public const string UnicodeVersion = "{version}";\n')
    lines.append(f"    /// <summary>{len(ranges)} sorted, non-overlapping ranges covering U+0000..U+10FFFF: start, end, class.</summary>")
    lines.append("    private static readonly int[] Starts =")
    lines.append("    [")
    for i in range(0, len(ranges), 8):
        lines.append("        " + ", ".join(f"0x{lo:05X}" for lo, _, _ in ranges[i:i + 8]) + ",")
    lines.append("    ];\n")
    lines.append("    private static readonly int[] Ends =")
    lines.append("    [")
    for i in range(0, len(ranges), 8):
        lines.append("        " + ", ".join(f"0x{hi:05X}" for _, hi, _ in ranges[i:i + 8]) + ",")
    lines.append("    ];\n")
    lines.append("    private static readonly BidiClass[] Classes =")
    lines.append("    [")
    for i in range(0, len(ranges), 8):
        lines.append("        " + ", ".join(f"BidiClass.{cls}" for _, _, cls in ranges[i:i + 8]) + ",")
    lines.append("    ];")
    lines.append("}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def emit_brackets(version: str, pairs: list[tuple[int, int, str]], out: Path) -> None:
    lines = [HEADER.format(version=version, source="BidiBrackets.txt")]
    lines.append("namespace MatPlotLibNet.Rendering.Text;\n")
    lines.append("internal static partial class BidiBrackets")
    lines.append("{")
    lines.append(f'    public const string UnicodeVersion = "{version}";\n')
    lines.append(f"    /// <summary>{len(pairs)} bracket code points, sorted: the code point, its pair, and whether it opens.</summary>")
    lines.append("    private static readonly int[] CodePoints =")
    lines.append("    [")
    for i in range(0, len(pairs), 8):
        lines.append("        " + ", ".join(f"0x{cp:04X}" for cp, _, _ in pairs[i:i + 8]) + ",")
    lines.append("    ];\n")
    lines.append("    private static readonly int[] Pairs =")
    lines.append("    [")
    for i in range(0, len(pairs), 8):
        lines.append("        " + ", ".join(f"0x{pair:04X}" for _, pair, _ in pairs[i:i + 8]) + ",")
    lines.append("    ];\n")
    lines.append("    private static readonly bool[] Opens =")
    lines.append("    [")
    for i in range(0, len(pairs), 8):
        lines.append("        " + ", ".join("true" if kind == "o" else "false" for _, _, kind in pairs[i:i + 8]) + ",")
    lines.append("    ];")
    lines.append("}")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def main() -> None:
    ucd = Path(sys.argv[1])
    out = Path(sys.argv[2])
    out.mkdir(parents=True, exist_ok=True)
    cv, ranges = read_bidi_classes(ucd / "DerivedBidiClass.txt")
    bv, pairs = read_brackets(ucd / "BidiBrackets.txt")
    if cv != bv:
        raise SystemExit(f"UCD version mismatch: DerivedBidiClass {cv} vs BidiBrackets {bv}")
    emit_classes(cv, ranges, out / "BidiClassTable.g.cs")
    emit_brackets(bv, pairs, out / "BidiBrackets.g.cs")
    print(f"UCD {cv}: {len(ranges)} class ranges, {len(pairs)} bracket entries -> {out}")


if __name__ == "__main__":
    main()
